create table events (
    id bigint generated by default as identity,
    name varchar(255),
    description TEXT,
    link varchar(255),
    date_start TIMESTAMP,
    date_end TIMESTAMP,
    primary key (id)
);

create table events_tag (
   id bigint generated by default as identity,
   id_event bigint,
   name varchar(255),
   primary key (id)
);

alter table events_tag
    add constraint events_tag_fk_events
        foreign key (id_event) references events;