create table events (
    id bigint generated by default as identity,
    name varchar(255) not null,
    description TEXT,
    link varchar(255) not null,
    date_start TIMESTAMP,
    date_end TIMESTAMP,
    primary key (id)
);

create table tags (
    id bigint generated by default as identity,
    name varchar(255) not null,
    primary key (id)
);

create table events_tag (
   id_tag bigint not null,
   id_event bigint not null
);

alter table events_tag
    add constraint events_tag_fk_events
        foreign key (id_event) references events;

alter table events_tag
    add constraint events_tag_fk_tags
        foreign key (id_tag) references tags;